# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='test.proto',
  package='hello',
  serialized_pb='\n\ntest.proto\x12\x05hello\"\x1c\n\x0bTestMessage\x12\r\n\x05hello\x18\x01 \x01(\t')




_TESTMESSAGE = descriptor.Descriptor(
  name='TestMessage',
  full_name='hello.TestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hello', full_name='hello.TestMessage.hello', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=49,
)



class TestMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTMESSAGE
  
  # @@protoc_insertion_point(class_scope:hello.TestMessage)

# @@protoc_insertion_point(module_scope)
